name: CI Quand-tine

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # ----- SERVER -----
      - name: Install server dependencies
        working-directory: server
        run: npm ci

      # ----- CLIENT -----
      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Build client (Vite)
        working-directory: client
        run: npm run build